/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "surface-container-lowest": "#0a0e14",
        "surface-tint": "#ffb955",
        "secondary-fixed-dim": "#bbc7df",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#291800",
        "outline": "#9f8e7a",
        "surface": "#10141a",
        "primary": "#ffc880",
        "primary-fixed": "#ffddb4",
        "tertiary-fixed-dim": "#7cd0ff",
        "on-surface-variant": "#d7c3ae",
        "surface-container": "#1c2026",
        "secondary": "#bbc7df",
        "on-tertiary-container": "#004d6a",
        "inverse-surface": "#dfe2eb",
        "surface-bright": "#353940",
        "surface-container-high": "#262a31",
        "on-secondary-container": "#adb9d1",
        "on-primary-fixed-variant": "#633f00",
        "on-primary": "#452b00",
        "tertiary-fixed": "#c4e7ff",
        "tertiary": "#9bd9ff",
        "background": "#10141a",
        "on-tertiary-fixed-variant": "#004c69",
        "surface-container-highest": "#31353c",
        "tertiary-container": "#3ac2ff",
        "on-primary-container": "#644000",
        "inverse-on-surface": "#2d3137",
        "on-error": "#690005",
        "on-tertiary": "#00344a",
        "primary-fixed-dim": "#ffb955",
        "primary-container": "#f5a623",
        "secondary-fixed": "#d7e3fc",
        "error-container": "#93000a",
        "surface-variant": "#31353c",
        "inverse-primary": "#835500",
        "surface-container-low": "#181c22",
        "on-secondary-fixed": "#101c2e",
        "on-surface": "#dfe2eb",
        "on-background": "#dfe2eb",
        "surface-dim": "#10141a",
        "on-secondary": "#253144",
        "secondary-container": "#3e495e",
        "on-tertiary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#3c475b",
        "outline-variant": "#524534"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "jetbrains": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
